name: Test Action

on:
  workflow_dispatch:

jobs:
  dryrun:
    name: Test Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check spelling
        uses: crate-ci/typos@bdcaedb080584d2f4f93f1da48df4645149adb7f

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: 'arn:aws:iam::012345678901:role/FooBarAction'
          aws-region: ap-northeast-1

